server:
  port: 8092
  tomcat:
    max-http-form-post-size: "-1"
      
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp    
  datasource: # Mybatis dataSource 연결
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rocketdb.cushblmt4tin.ap-northeast-2.rds.amazonaws.com/rocketdb?characterEncoding=utf-8
    username: root
    password: root1234
  
  devtools: # 서버 자동 시작
    livereload:
      enabled: true
mybatis: 
  type-aliases-package: com.yosi.myapp #mybatis에서 팩키지 생략 할 수 있도록 설정
  mapper-locations: mapper/*Mapper.xml 